version: '3'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    image: demo-lock:latest
    ports:
      - "8081:8080"  # 映射应用1的端口到主机的8081端口

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    image: demo-lock:latest
    ports:
      - "8082:8080"  # 映射应用2的端口到主机的8082端口
